import Head from 'next/head'
import { CryptoFullComponent } from '../components/crypto/CryptoFullComponent'
// import { Inter } from '@next/font/google'
import Footer from '../components/Footer'

// const inter = Inter({ subsets: ['latin'] })

export default function Cryptos() {

    return (
        <>
            <Head>
                <title>Crypto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=''>

                <CryptoFullComponent />
                <Footer /> 
            </div>
        </>
    )
}