import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '../components/Footer'
import FavoriteComponent from '../components/crypto/FavoriteComponent'

const inter = Inter({ subsets: ['latin'] })

export default function FavoriteCryptos() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=''>
                <FavoriteComponent />
                <Footer />
            </div>
        </>
    )
}