import Head from 'next/head'
// import { Inter } from '@next/font/google'
import Footer from '../components/Footer'
import SearchComponent from '../components/SearchComponent'

// const inter = Inter({ subsets: ['latin'] })

export default function Searc() {

    return (
        <>
            <Head>
                <title>Crypto search</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=''>

                <SearchComponent />
                <div className='fixed bottom-0 w-full pb-3 bg-gray-100'>
                    <Footer />
                </div>
            </div>
        </>
    )
}